---
name: Extract user data

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Extract
        run: go run ./cmd/extract

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f public/users/
          git commit --allow-empty -m "Extract user data"

      - name: Push
        run: git push -f origin main:dist
